version: '3.4'

services:
  geta-instanttemplates-sample-web:
    image: ${DOCKER_REGISTRY-}geta-instanttemplates-sample-web
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      geta-instanttemplates-network:
        ipv4_address: 172.16.238.51
    depends_on:
     - geta-instanttemplates-sample-db
    volumes: 
      - ../../src/module/:C:/data/
    mac_address: 84-69-95-6C-7F-85
  geta-instanttemplates-sample-db:
    image: microsoft/mssql-server-windows-developer:1709
    environment:
     - ACCEPT_EULA=Y
     - sa_password=Templ@tes123
     - attach_dbs=[{'dbName':'EPiServerDB_9e95eb3f','dbFiles':['C:\\data\\EPiServerDB_9e95eb3f.mdf','C:\\data\\EPiServerDB_9e95eb3f_log.ldf']}]
    volumes: 
      - ../Geta.InstantTemplates.Sample/App_Data:C:/data/
    networks: 
      geta-instanttemplates-network:
        ipv4_address: 172.16.238.52
networks: 
  geta-instanttemplates-network:
    ipam:
      driver: default
      config:
         - subnet: '172.16.238.0/24'
